#!/bin/sh

psfufo2glyphs source/BusraUprightDesign.designspace source/masters/BusraUprightDesign.glyphs
psfufo2glyphs source/BusraUprightRB.designspace source/masters/BusraUprightRB.glyphs
psfufo2glyphs source/BusraUprightRBXL.designspace source/masters/BusraUprightRBXL.glyphs
